services:
  app:
    container_name: biryukova-doc-app
    ports:
      - "8090:80"
    environment:
      APP_URL: http://localhost:8090
  db:
    container_name: biryukova-doc-db
    ports:
      - "3307:3306"
